/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$index_scaml {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n    <link href=\"/assets/css/style.css\" rel=\"stylesheet\"/>\n  </head>\n  <body>\n    <div class=\"container\">\n      <h1>es-discuss browser</h1>\n      <form action=\"#\" method=\"get\">\n        <input type=\"text\" placeholder=\"operator overloading, noSuchMethod, proxies\"/>\n      </form>\n      <div id=\"log\"></div>\n      <div id=\"timeline\">\n        <div id=\"chart\"></div>\n        <div id=\"axis\"></div>\n      </div>\n      <div id=\"summary\">\n        <div id=\"counter\"></div>\n        <div id=\"authors\"></div>\n      </div>\n      <div id=\"results\"></div>\n      \n    </div>\n    <script src=\"/assets/js/mootools.js\"></script>\n    <script src=\"/assets/js/mootools.more.js\"></script>\n    <script src=\"/assets/js/main.js\"></script>\n  </body>\n</html>\n" );
    }
  }
}


class $_scalate_$index_scaml extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$index_scaml.$_scalate_$render(context)
}
